name: www.brinquedinhosadulto30mais.com.br deployment

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: echo Building the app

    # deploy desenvolvimento
    deploy-development: 
        runs-on: ubuntu-latest
        environment:
            name: development
            url: ${{vars.URL}}
        needs: build
        steps: 
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: Configurar chave SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan -p 65002 147.93.37.136 >> ~/.ssh/known_hosts            

            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main           
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: ""
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}

    # deploy staging
    deploy-staging: 
        runs-on: ubuntu-latest
        environment:
            name: staging
            url: ${{vars.URL}}
        needs: deploy-development
        steps: 
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: Configurar chave SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan -p 65002 147.93.37.136 >> ~/.ssh/known_hosts
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: ""
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}

    # deploy production
    deploy-production: 
        runs-on: ubuntu-latest
        environment:
            name: production
            url: ${{vars.URL}}
        needs: deploy-staging
        steps: 
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: Configurar chave SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan -p 65002 147.93.37.136 >> ~/.ssh/known_hosts
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: ""
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}