name: www.brinquedinhosadulto30mais.com.br deployment

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: echo Building the app

    # deploy desenvolvimento
    deploy-development: 
        runs-on: ubuntu-latest
        environment:
            name: development
            url: ${{vars.URL}}
        needs: build
        steps: 
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              
    
    