name: www.brinquedinhosadulto30mais.com.br deployment

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: echo Building the app

    # deploy desenvolvimento
    deploy-development: 
        runs-on: ubuntu-latest
        environment:
            name: development
            url: ${{vars.URL}}
        needs: build
        steps: 
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
            - name: Teste SSH manual
              run: ssh -i ~/.ssh/deploy_key_u907364100_1738968201884 -o StrictHostKeyChecking=no u907364100@147.93.37.136 -p 65002 "echo Conectado!"

              
    