name: Testar Secret SSH

on: 
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Testar se a chave está disponível
        run: |
          if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "❌ Chave SSH não encontrada!"
            exit 1
          else
            echo "✅ Chave SSH está configurada!"
          fi
