name: Testar Secret SSH

on: 
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando Secret
        run: |
          if [ -n "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "✅ Secret está configurado!"
          else
            echo "❌ Secret não foi encontrado!"
            exit 1
          fi

